services:
  - type: web
    name: random-chat
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: SuperStrongSecret123
